# Generated by Django 4.0.6 on 2024-02-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.CharField(default='Order Placed', max_length=250),
        ),
    ]
