# Generated by Django 4.0.6 on 2024-02-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_order_details_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order_Placed', 'Order Placed'), ('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='Order_Placed', max_length=20),
        ),
    ]
