# Generated by Django 4.0.6 on 2024-03-01 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_orderitem_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderSummary',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
