# Generated by Django 5.1.3 on 2024-11-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_order_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Orders'},
        ),
    ]
